# 서버 설정
server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
# 뷰리졸버 설정
spring:
  mvc: 
   view:
    prefix: /WEB-INF/jblog/
    suffix: .jsp

# 데이터 소스 설정
  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
     username: sa
     password: 
      
# JPA 설정
  jpa: 
   open-in-view: true
   database-platform: org.hibernate.dialect.H2Dialect
   show-sql: true
   hibernate:
     ddl-auto: update 
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  
       use-new-id-generator-mappings: false
   properties:
       hibernate: 
         format_sql: true
         